title: Brain Implantations
description: Rendering of intracranial EEG implantations in epilepsy patients at the University of Pennsylvania.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
